config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'

  resources :feeds
  resources :entries do
    get :rss_reader, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
# Entry model
class Entry < ActiveRecord::Base
  belongs_to :feed, inverse_of: :entries

  scope :sort_by_published_date, lambda {
    order(published_date: :desc)
  }
end

app/models/feed.rb
# Feed model, contains data related to feed and feed has many entries
class Feed < ActiveRecord::Base
  has_many :entries, dependent: :destroy, inverse_of: :feed
  validates :url, presence: :true,
                  uniqueness: true,
                  format: {
                    with: URI::regexp,
                    message: 'Please provide valid url'
                  }
  validates :name, presence: :true

  after_save :parse_feed

  def parse_feed
    RssParser.new(self).parse!
  end
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
# Entries controller
class EntriesController < ApplicationController
  def rss_reader
    @entries = Entry.sort_by_published_date.paginate(
      page: params[:page],
      per_page: 10
    )
  end
end

app/controllers/feeds_controller.rb
# FeedsController
class FeedsController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :find_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.paginate(
      page: params[:page],
      per_page: 5
    )
  end

  def new
    @feed = Feed.new
  end

  def show
  end

  def create
    @feed = Feed.new(feed_params)
    if @feed.save
      flash[:success] = 'Feed added successfully!'
      redirect_to feeds_path
    else
      flash[:danger] = 'Unable to save'
      render :new
    end
  end

  def edit
  end

  def update
    if @feed.update(feed_params)
      flash[:success] = 'feed updated successfully!'
    else
      flash[:danger] = 'Error!'
    end
    redirect_to feeds_path
  end

  def destroy
    @feed.destroy
    flash[:success] = 'Feed deleted successfully!'
    redirect_to feeds_path
  end

  private

  def find_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:name, :url, :description)
  end

  def authenticate
    return if Rails.env.test?
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['AUTH_USERNAME'] &&
        password == ENV['AUTH_PASSWORD']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/rss_reader.html.haml
#wrap
  .container.text-middle.page-header
    %h1 Rss Reader
  %ul
    - @entries.each do |entry|
      %li
        = link_to(entry.title, entry.url, :target => "_blank")
  = will_paginate @entries, renderer: BootstrapPagination::Rails

app/views/feeds/_form.html.haml
= form_for(@feed) do |f|
  - if @feed.errors.any?
    #error_explanation.error.error_flash
      %ul
        - @feed.errors.full_messages.each do |message|
          %li= message
  .field.form-horizontal.clearfix
    .form-group
      = f.label('Name *', class: 'mandatory col-sm-2 control-label')
      .col-sm-8
        = f.text_field :name, placeholder: 'Name', maxlength: '55', class: 'form-control', required: true
    .form-group
      = f.label('URL *', class: 'mandatory col-sm-2 control-label')
      .col-sm-8
        = f.url_field :url, placeholder: 'Url', class: 'form-control', required: true
    .form-group
      = f.label('Description', class: 'mandatory col-sm-2 control-label')
      .col-sm-8
        = f.text_area :description, placeholder: 'Description', maxlength: '255', class: 'form-control'

    .form-group
      .col-sm-8.col-sm-offset-2
        = f.submit 'Add', class: 'btn btn-primary'
        = link_to 'Cancel', feeds_path

app/views/feeds/edit.html.haml
#wrap
  .custom-page-header
    .container
      %h1= 'Edit Feed'
  .container
    = render 'form'

app/views/feeds/index.html.haml
#wrap
  .container.text-middle.page-header
    %h1 Your Feeds
    .container.col-sm-8.col-sm-offset-2
      = link_to 'Add', new_feed_path, { class: 'pull-right btn btn-primary add-feed'}
      = link_to 'RSS Reader', rss_reader_entries_path, { class: 'pull-right btn btn-primary'}
  .container
    %table.table.table-striped{"data-sort-name" => "name", "data-sort-order" => "desc"}
      %thead
        %tr
          %th{"data-field" => "name", "data-sortable" => "true"} Name
          %th{"data-field" => "url", "data-sortable" => "true"} URL
          %th{"data-field" => "desc", "data-sortable" => "false"} Description
      %tbody
        - @feeds.each do |feed|
          %tr
            %td= feed.name
            %td= feed.url
            %td= feed.description
            %td
              = link_to 'View', feed_path(feed)
            %td
              = link_to 'Edit', edit_feed_path(feed)
            %td
              = link_to 'Destroy',feed, method: :delete, data: { confirm: 'Are you sure?' }
    = will_paginate @entries, renderer: BootstrapPagination::Rails

app/views/feeds/new.html.haml
#wrap
  .custom-page-header
    .container
      %h1= 'New Feed'
  .container
    = render 'form'

app/views/feeds/show.html.haml
%p#notice= notice
.jumbotron
  %p
    %strong= 'Name :'
    = @feed.name
    %br
    %strong= 'URL'
    = @feed.url
    %br
    %strong= 'Description'
    = @feed.description
  = link_to 'edit', edit_feed_path(@feed)
  |
  = link_to 'back', feeds_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %title= RSSReader
    = favicon_link_tag 'favicon.ico'
    %meta{charset: 'utf-8'}
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrap
      = render 'shared/header'
      .container
        .row
          .col-md-12
            - flash.each do |key, value|
              %div{class: "flash-message alert alert-#{key}"}= value
            = yield
    = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer
  .container
    %p Simple RSS Reader

app/views/shared/_header.html.haml
.container
  .page-header
    %h1= link_to('Simple RSS Reader', root_path)
  %p Add your feeds, you can edit/view/destroy feeds
  %p RSS reader will show all latest posts from all feeds sorted by date. Clicking on title will open original article page in new tab/window